* youtube-dl helper script
This program just allows me to select a format from a list and download it with a single command.
I may make this more sophisticated in the future.

** Usage
You must have the following on your system:
- youtube-dl
- babashka

Make the script executable with ~chmod +x script.clj~.
Copy or make a symbolic link to =script.clj= into a directory on your ~PATH~.

For example, I named the link to the script ~ytf~ (youtube format).
#+begin_src shell
  ytf [youtube-link]
#+end_src

** License
youtube-dl helper script
Copyright © 2021 Christian Westrom

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.

https://www.gnu.org/graphics/gplv3-or-later.png]]
